### ISSUE TITLE
New line handling on Windows?

### ISSUE THREAD

**Issue by stevefan1999-personal** [Source2ZE/CleanerCS2#5]
Seems like it leaves a trail of new lines when the filter is applied.
![{5F7A162B-19C1-4DF3-896D-5B0883772FBF}](https://github.com/user-attachments/assets/cc99c1cf-40cb-49cc-b7e3-dc1a45e5d00a)
```
// Write regular expression in here to prevent them from being printed in the console
.*UNEXPECTED LONG FRAME DETECTED.*\n
.*weapon services didn't find a shoot position.*\n
.*generating substitute command \d+ from \d+.*\n
.*Long frame.*\n
```

**Comment by Vauff** [comment]
It's not that Cleaner is causing this, but rather something you're filtering also happens to print new lines (separately, thus not being caught), and you're only noticing them now since you filtered everything around it.

Unfortunately, filtering standalone new line prints is impractical, but everything you're filtering has official toggles already available anyways:
```
engine_frametime_warnings_enable 0
log_verbosity Shooting off
log_verbosity "SV CommandQueue" off
```
